name: healthcheck

on:
  push:
    branches: ['*']
  schedule:
    - cron: '*/5 * * * *'

jobs:
  healthcheck:
    strategy:
      matrix:
        url: [ "https://ccd.run.place", "https://ip-info.run.place", "https://weather.line.pm"]
    runs-on: ubuntu-24.04
    steps:
      - name: Check availability of ${{ matrix.url }}
        run: curl -sLIf -m 15 -o /dev/null --retry 5 --retry-all-errors "${{ matrix.url }}/healthz" || exit 1
