name: healthcheck

on:
  push:
    branches: ['*']

jobs:
  healthcheck:
    strategy:
      matrix:
        url: [ "https://ccd.run.place", "https://ip-info.run.place", "https://weather.line.pm" ]
    runs-on: ubuntu-24.04
    steps:
      - name: Check availability of ${{ matrix.url }}
        run: test $(curl --silent --location --head --connect-timeout 15 --output /dev/null --write-out "%{http_code}" "${{ matrix.url }}") -eq 200 || exit 1