name: healthcheck

on:
  push:
    branches: ['*']
  schedule:
    - cron: '0 * * * *'

jobs:
  check-site:
    strategy:
      matrix:
        url: [ "https://ccd.oncook.top", "https://ip-info.oncook.top", "https://weather.oncook.top"]
    runs-on: ubuntu-24.04
    steps:
      - name: Check availability of ${{ matrix.url }}
        run: curl -sLIf -m 15 -o /dev/null --retry 5 --retry-all-errors "${{ matrix.url }}/healthz" || exit 1
